import "./Properties.css";

const Properties = [
  // ---------- HOUSES ----------
  {
    id: 1,
    title: "Independent House",
    category: "house",
    price: "25,00,000 INR",
    address: "123 Ameerpet, Hyderabad, Telangana",
    bhk: "2 BHK",
    bathrooms: "3 Bathrooms",
    area: "285 Square Yards",
    age: "5 Years Old",
    status: "Sale",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Raju Kumar", phone: "+91 9876543210", email: "raju@gmail.com" },
    description: "A beautifully designed modern house located in a peaceful neighborhood...",
    images: ["/images/house1.image1.png", "/images/house1.image2.png", "/images/house1.image3.png"],
  },
  {
    id: 2,
    title: "Traditional House",
    category: "house",
    price: "4,50,000 INR",
    address: "78 Banjara Hills, Hyderabad, Telangana",
    bhk: "3 BHK",
    bathrooms: "3 Bathrooms",
    area: "175 Square Yards",
    age: "7 Years Old",
    status: "Buy",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Rahul Sharma", phone: "+91 9123456780", email: "rahul@gmail.com" },
    description: "Premium luxury villa with elegant interiors and landscaped garden...",
    images: ["/images/house2.image1.png", "/images/house2.image2.png", "/images/house2.image3.png"],
  },
  {
    id: 3,
    title: "Family Home",
    category: "house",
    price: "3,20,000 INR",
    address: "45 Boduppal, Hyderabad, Telangana",
    bhk: "2 BHK",
    bathrooms: "3 Bathrooms",
    area: "235 Square Yards",
    age: "1 Year Old",
    status: "Sale",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Jahanavi Reddy", phone: "+91 9234567810", email: "jahanavi@gmail.com" },
    description: "Cozy family home in a friendly neighborhood...",
    images: ["/images/house3.image1.png", "/images/house3.image2.png", "/images/house3.image3.png"],
  },
  {
    id: 4,
    title: "City Apartment",
    category: "house",
    price: "28,00,000 INR",
    address: "22 Punjagutta, Hyderabad, Telangana",
    bhk: "2 BHK",
    bathrooms: "3 Bathrooms",
    area: "205 Square Yards",
    age: "5 Years Old",
    status: "Buy",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Srinika Patel", phone: "+91 9345678120", email: "srinika@gmail.com" },
    description: "Modern city apartment located in the heart of downtown...",
    images: ["/images/house4.image1.png", "/images/house4.image2.png", "/images/house4.image3.png"],
  },
  {
    id: 5,
    title: "Beach House",
    category: "house",
    price: "5,20,000 INR",
    address: "99 Miyapur, Hyderabad, Telangana",
    bhk: "3 BHK",
    bathrooms: "3 Bathrooms",
    area: "195 Square Yards",
    age: "8 Years Old",
    status: "Sale",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Keerthana", phone: "+91 9456781230", email: "keerthana@gmail.com" },
    description: "Beautiful beach house with stunning sea views...",
    images: ["/images/house5.image1.png", "/images/house5.image2.png", "/images/house5.image3.png"],
  },
  {
    id: 6,
    title: "Country Home",
    category: "house",
    price: "3,00,000 INR",
    address: "12 Basavanagudi, Bangalore, Karnataka",
    bhk: "2 BHK",
    bathrooms: "3 Bathrooms",
    area: "150 Square Yards",
    age: "9 Years Old",
    status: "Buy",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Shankar", phone: "+91 9567812340", email: "shankar@gmail.com" },
    description: "Peaceful country home surrounded by greenery...",
    images: ["/images/house6.image1.png", "/images/house6.image2.png", "/images/house6.image3.png"],
  },
  {
    id: 7,
    title: "Mountain Villa",
    category: "house",
    price: "4,80,000 INR",
    address: "88 Central Bangalore, Karnataka",
    bhk: "3 BHK",
    bathrooms: "3 Bathrooms",
    area: "200 Square Yards",
    age: "10 Years Old",
    status: "Buy",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Akhilesh", phone: "+91 9678123450", email: "akhilesh@gmail.com" },
    description: "Elegant mountain villa with breathtaking views...",
    images: ["/images/house7.image1.png", "/images/house7.image2.png", "/images/house7.image3.png"],
  },
  {
    id: 8,
    title: "Smart Home",
    category: "house",
    price: "4,10,000 INR",
    address: "14 Indiranagar, Bangalore, Karnataka",
    bhk: "2 BHK",
    bathrooms: "3 Bathrooms",
    area: "185 Square Yards",
    age: "5 Years Old",
    status: "Buy",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Srinivas", phone: "+91 9781234560", email: "srinivas@gmail.com" },
    description: "Fully automated smart home with advanced security systems...",
    images: ["/images/house8.image1.png", "/images/house8.image2.png", "/images/house8.image3.png"],
  },
  {
    id: 9,
    title: "Modern Home",
    category: "house",
    price: "4,20,000 INR",
    address: "55 Basavanagudi, Bangalore, Karnataka",
    bhk: "3 BHK",
    bathrooms: "3 Bathrooms",
    area: "175 Square Yards",
    age: "6 Years Old",
    status: "Buy",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Ravi", phone: "+91 9891234567", email: "ravi@gmail.com" },
    description: "Stylish modern home with elegant interiors...",
    images: ["/images/house9.image1.png", "/images/house9.image2.png", "/images/house9.image3.png"],
  },
  {
    id: 10,
    title: "Classic House",
    category: "house",
    price: "3,50,000 INR",
    address: "31 Whitefield, Bangalore, Karnataka",
    bhk: "2 BHK",
    bathrooms: "3 Bathrooms",
    area: "165 Square Yards",
    age: "7 Years Old",
    status: "Buy",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Padma", phone: "+91 9901234567", email: "padma@gmail.com" },
    description: "Traditional classic house with wooden interiors...",
    images: ["/images/house10.image1.png", "/images/house10.image2.png", "/images/house10.image3.png"],
  },

  // ---------- COMMERCIAL ----------
  {
    id: 11,
    title: "IT Corporate Office",
    category: "commercial",
    price: "9,50,000 INR",
    address: "HiTech City, Hyderabad, Telangana",
    bhk: "Open Workspace",
    bathrooms: "4 Washrooms",
    area: "4500 Sq Ft",
    age: "2 Years Old",
    status: "Lease",
    paymentOptions: ["Monthly Rent", "Yearly Lease"],
    contact: { name: "Vikram Rao", phone: "+91 9876501234", email: "vikram.office@gmail.com" },
    description: "Fully furnished IT office with conference rooms...",
    images: ["/images/office1.image1.png", "/images/office1.image2.png", "/images/office1.image3.png"],
  },
  {
    id: 12,
    title: "Startup Office Space",
    category: "commercial",
    price: "6,80,000 INR",
    address: "Madhapur, Hyderabad, Telangana",
    bhk: "Co-working Space",
    bathrooms: "3 Washrooms",
    area: "3200 Sq Ft",
    age: "1 Year Old",
    status: "Rent",
    paymentOptions: ["Monthly Rent"],
    contact: { name: "Suresh Kumar", phone: "+91 9765432109", email: "suresh.office@gmail.com" },
    description: "Modern startup-friendly office with flexible seating...",
    images: ["/images/office2.image1.png", "/images/office2.image2.png", "/images/office2.image3.png"],
  },
  {
    id: 13,
    title: "Business Park Office",
    category: "commercial",
    price: "12,00,000 INR",
    address: "Whitefield, Bangalore, Karnataka",
    bhk: "Commercial Office",
    bathrooms: "5 Washrooms",
    area: "6000 Sq Ft",
    age: "3 Years Old",
    status: "Sale",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Anand Mehta", phone: "+91 9812345098", email: "anand.office@gmail.com" },
    description: "Premium office space in business park with lift, parking...",
    images: ["/images/office3.image1.png", "/images/office3.image2.png", "/images/office3.image3.png"],
  },
  {
    id: 14,
    title: "Tech Park Office",
    category: "commercial",
    price: "10,20,000 INR",
    address: "Gachibowli, Hyderabad, Telangana",
    bhk: "Corporate Office",
    bathrooms: "4 Washrooms",
    area: "4800 Sq Ft",
    age: "2 Years Old",
    status: "Lease",
    paymentOptions: ["Monthly Rent", "Yearly Lease"],
    contact: { name: "Praveen Reddy", phone: "+91 9887654321", email: "praveen.office@gmail.com" },
    description: "Spacious tech park office with plug-and-play setup...",
    images: ["/images/office4.image1.png", "/images/office4.image2.png", "/images/office4.image3.png"],
  },
  {
    id: 15,
    title: "Downtown Corporate Office",
    category: "commercial",
    price: "11,75,000 INR",
    address: "MG Road, Bangalore, Karnataka",
    bhk: "Premium Office Space",
    bathrooms: "5 Washrooms",
    area: "5500 Sq Ft",
    age: "4 Years Old",
    status: "Sale",
    paymentOptions: ["EMI", "Full Payment"],
    contact: { name: "Karthik Shetty", phone: "+91 9976543210", email: "karthik.office@gmail.com" },
    description: "Premium downtown office with modern interiors...",
    images: ["/images/office5.image1.png", "/images/office5.image2.png", "/images/office5.image3.png"],
  },

  // ---------- RESIDENTIAL HOSTELS / PG ----------
  {
    id: 16,
    title: "Boys Hostel",
    category: "residential",
    price: "6,000 INR / Month",
    address: "Ameerpet, Hyderabad, Telangana",
    bhk: "Shared Rooms",
    bathrooms: "Common Bathrooms",
    area: "Hostel Building",
    age: "4 Years Old",
    status: "Rent",
    paymentOptions: ["Monthly Payment"],
    contact: { name: "Ramesh", phone: "+91 9123456701", email: "ramesh.hostel@gmail.com" },
    description: "Affordable boys hostel with WiFi, power backup, mess facility...",
    images: ["/images/hostel1.image1.png", "/images/hostel1.image2.png", "/images/hostel1.image3.png"],
  },
  {
    id: 17,
    title: "Girls Hostel",
    category: "residential",
    price: "7,500 INR / Month",
    address: "Kukatpally, Hyderabad, Telangana",
    bhk: "Shared Rooms",
    bathrooms: "Attached & Common",
    area: "Hostel Building",
    age: "2 Years Old",
    status: "Rent",
    paymentOptions: ["Monthly Payment"],
    contact: { name: "Sunitha", phone: "+91 9345678901", email: "sunitha.hostel@gmail.com" },
    description: "Secure girls hostel with CCTV, biometric entry...",
    images: ["/images/hostel2.image1.png", "/images/hostel2.image2.png", "/images/hostel2.image3.png"],
  },
  {
    id: 18,
    title: "Working Professionals Hostel",
    category: "residential",
    price: "8,500 INR / Month",
    address: "Electronic City, Bangalore, Karnataka",
    bhk: "Single & Shared Rooms",
    bathrooms: "Attached Bathrooms",
    area: "PG Building",
    age: "1 Year Old",
    status: "Rent",
    paymentOptions: ["Monthly Payment"],
    contact: { name: "Mahesh", phone: "+91 9988776655", email: "mahesh.pg@gmail.com" },
    description: "Premium PG for working professionals with AC rooms...",
    images: ["/images/hostel3.image1.png", "/images/hostel3.image2.png", "/images/hostel3.image3.png"],
  },
  {
    id: 19,
    title: "Luxury Girls Hostel",
    category: "residential",
    price: "9,000 INR / Month",
    address: "Madhapur, Hyderabad, Telangana",
    bhk: "Single & Shared Rooms",
    bathrooms: "Attached Bathrooms",
    area: "Hostel Building",
    age: "1 Year Old",
    status: "Rent",
    paymentOptions: ["Monthly Payment"],
    contact: { name: "Kavitha", phone: "+91 9876543211", email: "kavitha.hostel@gmail.com" },
    description: "Premium girls hostel with AC rooms, CCTV security...",
    images: ["/images/hostel4.image1.png", "/images/hostel4.image2.png", "/images/hostel4.image3.png"],
  },
  {
    id: 20,
    title: "Budget Boys Hostel",
    category: "residential",
    price: "5,000 INR / Month",
    address: "Dilsukhnagar, Hyderabad, Telangana",
    bhk: "Shared Rooms",
    bathrooms: "Common Bathrooms",
    area: "PG Building",
    age: "5 Years Old",
    status: "Rent",
    paymentOptions: ["Monthly Payment"],
    contact: { name: "Sathish", phone: "+91 9765432190", email: "sathish.hostel@gmail.com" },
    description: "Affordable budget hostel for students with basic amenities...",
    images: ["/images/hostel5.image1.png", "/images/hostel5.image2.png", "/images/hostel5.image3.png"],
  },
  {
    id: 21,
    title: "Executive PG Hostel",
    category: "residential",
    price: "10,500 INR / Month",
    address: "Whitefield, Bangalore, Karnataka",
    bhk: "Single Rooms",
    bathrooms: "Attached Bathrooms",
    area: "PG Building",
    age: "2 Years Old",
    status: "Rent",
    paymentOptions: ["Monthly Payment"],
    contact: { name: "Naveen Kumar", phone: "+91 9898765432", email: "naveen.pg@gmail.com" },
    description: "High-end executive PG with fully furnished rooms...",
    images: ["/images/hostel6.image1.png", "/images/hostel6.image2.png", "/images/hostel6.image3.png"],
  },
];

export default Properties;
